"""Markdown serialization for investigation report downloads."""

from __future__ import annotations

from typing import Any


def investigation_report_markdown(payload: dict[str, Any]) -> str:
    score = payload.get("faithfulnessScore")
    score_line = f"{float(score) * 100:.0f}%" if score is not None else "N/A"
    grounded = payload.get("isGrounded")
    grounded_line = (
        "Verified Grounded"
        if grounded is True
        else ("Low Grounding" if grounded is False else "N/A")
    )
    latency = payload.get("latencyMs")
    latency_line = f"{float(latency):.1f} ms" if latency is not None else "N/A"

    lines: list[str] = [
        "# Incident Investigation Report",
        "",
        "## Report Header",
        "",
        f"- **Title:** {payload.get('title') or 'Incident Investigation Report'}",
        f"- **Timestamp (UTC):** {payload.get('timestamp') or '—'}",
        f"- **Session ID:** `{payload.get('sessionId') or '—'}`",
        f"- **Route / Tool Used:** `{payload.get('toolUsed') or '—'}`",
        f"- **Faithfulness Score:** {score_line} ({grounded_line})",
        f"- **Latency:** {latency_line}",
        f"- **Cache:** {'Hit' if payload.get('cached') else 'Miss'}",
        "",
        "## Original Question",
        "",
        str(payload.get("query") or "—"),
        "",
        "## Rewritten Query",
        "",
        str(payload.get("rewrittenQuery") or payload.get("query") or "—"),
        "",
        "## Investigation Synthesis",
        "",
        str(payload.get("answer") or payload.get("summary") or "—"),
        "",
        "## Root Cause Analysis",
        "",
        str(payload.get("rootCause") or "—"),
        "",
        "## Recommended Actions",
        "",
        str(payload.get("actionItems") or "—"),
        "",
        "## Citations & Reference Documents",
        "",
    ]

    citations = payload.get("citations") or []
    if not citations:
        lines.append("_No citations returned for this investigation turn._")
        lines.append("")
    else:
        for index, citation in enumerate(citations, start=1):
            lines.extend(
                [
                    f"### [{index}] `{citation.get('documentId') or 'unknown'}`",
                    "",
                    f"- **System:** {citation.get('systemName') or citation.get('system') or '—'}",
                    f"- **Severity:** {citation.get('severity') or '—'}",
                    f"- **Similarity:** {citation.get('score') if citation.get('score') is not None else '—'}",
                    "",
                    "```",
                    str(citation.get("chunkText") or "").strip() or "(empty excerpt)",
                    "```",
                    "",
                ]
            )

    unsupported = [
        str(item).strip() for item in (payload.get("unsupportedClaims") or []) if str(item).strip()
    ]
    lines.extend(["## Unsupported Claims", ""])
    if not unsupported:
        lines.append("_None flagged — all extracted claims were treated as grounded._")
        lines.append("")
    else:
        for index, claim in enumerate(unsupported, start=1):
            lines.append(f"{index}. {claim}")
        lines.append("")

    sql_result = payload.get("sqlQueryResult")
    if isinstance(sql_result, dict) and (sql_result.get("query") or sql_result.get("rows") is not None):
        lines.extend(
            [
                "## SQL Metrics Appendix",
                "",
                f"- **Interpretation:** {sql_result.get('interpretation') or '—'}",
                f"- **Row count:** {sql_result.get('rowCount', 0)}",
                "",
                "```sql",
                str(sql_result.get("query") or "").strip() or "-- (no query)",
                "```",
                "",
            ]
        )

    lines.append("---")
    lines.append("_Generated by Tech-Doc-Intelligence Agentic Incident Assistant._")
    lines.append("")
    return "\n".join(lines)
